### ISSUE TITLE
Problems with weeks overlapping at the turn of the year

### ISSUE THREAD

**Issue by bellisk** [liip/presence#42]
Clicking the link to increment the week by one, when the current week is 2014-53, takes you to week 2014-2. It should go to 2015-2.

Likewise, going back a week from 2015-1 takes you to 2014-0 (an error page). I guess it should go to 2015-52 or 2015-53. Maybe there is a problem with the weeks overlapping at the end of the year?

**Comment by maximgubar** [comment]
[JIRA ticket](https://jira.liip.ch/browse/INT-343) has been created
