### ISSUE TITLE
prefer full day appointments that are marked as "busy" over others

### ISSUE THREAD

**Issue by lsmith77** [liip/presence#44]
f.e. I currently have a multi week appointment that I am working on a specific project but when I have a "busy" appointment during that same timeframe (for example a vacation) it isn't shown.

http://presence.liip.ch/lukas.smith@liip.ch?week=2015-31&view=2&details=0

**Comment by maximgubar** [comment]
[JIRA ticket](https://jira.liip.ch/browse/INT-342) has been created
